name: Build and Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create updater token
        shell: pwsh
        run: |
            [System.IO.File]::WriteAllText(
            "build/updater-token.txt",
            "${{ secrets.GH_TOKEN_HOTEL }}"
            )

      - name: Build and publish
        run: npm run build -- --publish always
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}